/* ui_assets.h - GENERATED by scratch/gen_ui_assets.py. Do not edit. */
#ifndef UI_ASSETS_H
#define UI_ASSETS_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* 4bpp palettised sprite; palette[0] is the transparent index. */
typedef struct {
    uint16_t        w, h;
    uint16_t        stride;
    const uint16_t *palette;
    const uint8_t  *pixels;
} ui_sprite_t;

/* One glyph of a 4bpp anti-aliased proportional font. */
typedef struct {
    uint8_t  w, h;
    int8_t   xoff, yoff;
    uint8_t  advance;
    uint16_t offset;
} ui_glyph_t;

typedef struct {
    uint8_t           first, last;
    uint8_t           line_height, baseline;
    const ui_glyph_t *glyphs;
    const uint8_t    *blob;
} ui_font_t;

extern const ui_sprite_t ui_sprite_mascot_a;
extern const ui_sprite_t ui_sprite_mascot_b;
extern const ui_sprite_t ui_sprite_mascot_blink;
extern const ui_sprite_t ui_sprite_mascot_sad0;
extern const ui_sprite_t ui_sprite_mascot_sad1;
extern const ui_sprite_t ui_sprite_mascot_sad2;
extern const ui_sprite_t ui_sprite_sparkle_lg;
extern const ui_sprite_t ui_sprite_sparkle_sm;
extern const ui_sprite_t ui_sprite_heart;
extern const ui_sprite_t ui_sprite_capsule;

extern const ui_font_t ui_font_lg;
extern const ui_font_t ui_font_md;
extern const ui_font_t ui_font_sm;
extern const ui_font_t ui_font_num;

/* Theme colours sampled from the reference artwork (RGB565). */
#define THEME_FRAME_PINK  0xFF1C
#define THEME_BLUSH       0xFFFF

#ifdef __cplusplus
}
#endif

#endif /* UI_ASSETS_H */
