/**
 ******************************************************************************
 * @file      sysmem.c
 * @author    Generated by STM32CubeIDE
 * @brief     STM32CubeIDE System Memory calls file
 *
 *            For more information about which C functions
 *            need which of these lowlevel functions
 *            please consult the newlib libc manual
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* Includes */
#include <errno.h>
#include <stdint.h>
#include <stddef.h>

/**
 * Pointer to the current high watermark of the heap usage
 */
static uint8_t *__sbrk_heap_end = NULL;

/*
 * Session 11 fix (MedSight): this file's own doc comment already draws the
 * memory map as [.data][.bss][newlib heap][MSP stack] — but as of Session 11,
 * a THIRD allocator also starts at '_end': µT-Kernel's own knl_init_Imalloc()
 * (ms_osal.c / vendored mtk3_bsp2), which claims [_end, CNF_SYSTEMAREA_END)
 * as its own heap with no knowledge that newlib's _sbrk() considers that same
 * starting address its own. The two never coordinated, and every printf()
 * that lazily grows newlib's heap (stdio's internal per-stream buffer, on
 * first use) silently overwrote whatever the kernel's allocator had just
 * placed at '_end' — confirmed by planting diagnostic prints deep inside
 * knl_init_Imalloc()'s own free-list header and watching a printf() call a
 * few lines later corrupt it. NEWLIB_HEAP_RESERVE below is a small, fixed
 * arena carved out for newlib immediately after '_end'; the matching change
 * in mtk3_bsp2/sysdepend/stm32_cube/cpu/core/armv8m/sys_start.c starts the
 * kernel's own heap NEWLIB_HEAP_RESERVE bytes higher, so the two never
 * overlap. Both sides must agree on this same constant. */
#define NEWLIB_HEAP_RESERVE (8u * 1024u)

/**
 * @brief _sbrk() allocates memory to the newlib heap and is used by malloc
 *        and others from the C library
 *
 * @verbatim
 * ############################################################################
 * #  .data  #  .bss  #       newlib heap       #          MSP stack          #
 * #         #        #                         # Reserved by _Min_Stack_Size #
 * ############################################################################
 * ^-- RAM start      ^-- _end                             _estack, RAM end --^
 * @endverbatim
 *
 * This implementation starts allocating at the '_end' linker symbol
 * The '_Min_Stack_Size' linker symbol reserves a memory for the MSP stack
 * The implementation considers '_estack' linker symbol to be RAM end
 * NOTE: If the MSP stack, at any point during execution, grows larger than the
 * reserved size, please increase the '_Min_Stack_Size'.
 *
 * @param incr Memory size
 * @return Pointer to allocated memory
 */
void *_sbrk(ptrdiff_t incr)
{
  /* Session 12: '_end' is declared as an ARRAY, not a scalar. It is a linker
   * symbol marking the start of free RAM, and the pointer arithmetic below
   * deliberately walks NEWLIB_HEAP_RESERVE bytes past it. With the stock
   * 'extern uint8_t _end;' declaration GCC believes it is a one-byte object
   * and -Warray-bounds (which only runs at -O1 and above, so it fired in the
   * Release configuration but never in Debug) reported '&_end + 8192' as an
   * out-of-bounds subscript. Declaring it as an incomplete array states the
   * truth — the symbol has no size the compiler can know — and produces the
   * identical address with no warning. */
  extern uint8_t _end[]; /* Symbol defined in the linker script */
  extern uint8_t _estack; /* Symbol defined in the linker script */
  extern uint32_t _Min_Stack_Size; /* Symbol defined in the linker script */
  const uint32_t stack_limit = (uint32_t)&_estack - (uint32_t)&_Min_Stack_Size;
  /* Session 11: capped to NEWLIB_HEAP_RESERVE past _end, not all the way up
   * to the MSP stack limit — see the comment on NEWLIB_HEAP_RESERVE above. */
  const uint8_t *max_heap = (_end + NEWLIB_HEAP_RESERVE < (uint8_t *)stack_limit)
                              ? (_end + NEWLIB_HEAP_RESERVE)
                              : (uint8_t *)stack_limit;
  uint8_t *prev_heap_end;

  /* Initialize heap end at first call */
  if (NULL == __sbrk_heap_end)
  {
    __sbrk_heap_end = _end;
  }

  /* Protect heap from growing into the reserved MSP stack */
  if (__sbrk_heap_end + incr > max_heap)
  {
    errno = ENOMEM;
    return (void *)-1;
  }

  prev_heap_end = __sbrk_heap_end;
  __sbrk_heap_end += incr;

  return (void *)prev_heap_end;
}
